---
.rubocop.yml:
  default_configs:
    Layout/LineLength:
      Max: 260
    RSpec/NamedSubject:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
    Style/ClassAndModuleChildren:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 6.0'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 1.0'
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
        version: '~> 2.0'
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 4.0'
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri
      - gem: 'bolt'
        version: '~> 3.0'
        condition: 'ENV["GEM_BOLT"]'
      - gem: 'beaker-task_helper'
        version: '~> 1.9'
        condition: 'ENV["GEM_BOLT"]'
      # The Faraday requirements in orchestrator_client 0.7.1 causes Bundler to
      # resolve the dependency in unexpected ways and causes issues in CI
      - gem: 'orchestrator_client'
        version: '< 0.7.1'
        condition: 'ENV["GEM_BOLT"]'
      - gem: async
        version: '~> 1.30' # otherwise async 2.0.0(needs ruby >=3.1.0) is wrongly selected by bundler on jenkins while running with ruby 2.7.1
    ":system_tests":
      - gem: voxpupuli-acceptance
        version: '~> 3'

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  unmanaged: true
# puppet_url_without modules check in puppet-lint assumes any puppet:/// URL is
# using the module mount. pe_packages is a custom mount and doesn't need
# modules.
Rakefile:
  extra_disabled_lint_checks:
    - puppet_url_without_modules
  requires:
    - require: voxpupuli/acceptance/rake
      conditional: Gem.loaded_specs.key? 'voxpupuli-acceptance'
