---
.rubocop.yml:
  default_configs:
    Layout/LineLength:
      Max: 260
    RSpec/NamedSubject:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
    Style/ClassAndModuleChildren:
      Enabled: false
    Style/FileNull:
      Enabled: false
Gemfile:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
spec/spec_helper.rb:
  unmanaged: true
# puppet_url_without modules check in puppet-lint assumes any puppet:/// URL is
# using the module mount. pe_packages is a custom mount and doesn't need
# modules.
Rakefile:
  extra_disabled_lint_checks:
    - puppet_url_without_modules
