---
  .gitignore:
    paths:
      - '.*.sw?'

  # The Travis and Appveyor configurations for puppet_agent don't fit
  # in the module_sync model yet
  .travis.yml:
    unmanaged: true

  # Requires the bundler_args to be supported.
  # .travis.yml:
  #   dist: trusty
  #   script: 'bundle exec rake $CHECK'
  #   before_install:
  #     - bundle -v
  #     - rm Gemfile.lock || true
  #     - gem update --system
  #     - gem --version
  #     - bundle -v
  #   docker_sets:
  #   includes:
  #     # Disabling 1.8.7 as it no longer plays nice
  #     # - rvm: 1.8.7
  #     #   env: PUPPET_GEM_VERSION="~> 3.7.5"
  #     # - rvm: 1.8.7
  #     #   env: PUPPET_GEM_VERSION="~> 3.8.1"
  #     # Disabling as puppet-module-gems only supports ruby >= 2.1.X
  #     # - rvm: 1.9.3
  #     #   env: PUPPET_GEM_VERSION="~> 3.8.1"  FUTURE_PARSER="yes"

  #     - rvm: 2.4.1
  #       env: CHECK="validate lint"
  #     - rvm: 2.1.0
  #       env: PUPPET_GEM_VERSION="~> 3.8" FUTURE_PARSER="yes" CHECK=spec
  #     - rvm: 2.1.5
  #       env: PUPPET_GEM_VERSION="~> 4.0.0" CHECK=spec
  #     - rvm: 2.1.9
  #       env: PUPPET_GEM_VERSION="4.7.1" HIERA_GEM_VERSION="3.2.2" CHECK=spec
  #     - rvm: 2.1.9
  #       env: PUPPET_GEM_VERSION="~> 4.10" CHECK=spec
  #     - rvm: 2.4.1
  #       env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec

  Gemfile:
    required:
      ':development':
        # Gems built using puppet-module-gems utility
        - gem: 'puppet-module-posix-default-r#{minor_version}'
          platforms: 'ruby'
        - gem: 'puppet-module-win-default-r#{minor_version}'
          platforms:
            - 'mswin'
            - 'mingw'
            - 'x64_mingw'
        - gem: 'puppet-module-posix-dev-r#{minor_version}'
          platforms: 'ruby'
          version: '0.3.3'
        - gem: 'puppet-module-win-dev-r#{minor_version}'
          platforms:
            - 'mswin'
            - 'mingw'
            - 'x64_mingw'
          version: '0.0.7'
        # json_pure 2.0.2 added a requirement on ruby >= 2. We pin to json_pure <= 2.0.1
        # if using ruby 1.x
        - gem: json_pure
          version: '<= 2.0.1'
          condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
        - gem: fast_gettext
          version: '1.1.0'
          condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.1.0')"
        - gem: fast_gettext
          condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.1.0')"
        # Pin rspec-puppet 2.6.9 until https://github.com/rodjek/rspec-puppet/issues/663 is fixed
        - gem: 'rspec-puppet'
          version: '2.6.9'

  appveyor.yml:
    unmanaged: true

  # The default.yml file should not be updated yet as it doesn't fit
  # in the module_sync model yet
  'spec/acceptance/nodesets/default.yml':
    unmanaged: true

  Rakefile:
    extra_disabled_lint_checks:
    - 'disable_140chars'
    - 'disable_puppet_url_without_modules'
    - 'disable_class_inherits_from_params_class'
    - 'disable_documentation'
    - 'disable_single_quote_string_with_variables'
    - 'disable_only_variable_string'

  .gitattributes:
    # Currently the only ERB template is for the Windows install
    # batch file and should always be CRLF
    exclude:
    - "*.erb"

  NOTICE:
    copyright_holders:
      - name: 'Puppet, Inc.'
        begin: 2015
