HOSTS:
  debian-13-x64:
    roles:
      - target
    platform: debian-13-amd64
    hypervisor: docker
    image: debian:13
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get update && apt-get install -y net-tools wget locales strace lsof && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen'
CONFIG:
  trace_limit: 200
