HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
    vagrant_memsize: 3072

  agent:
    roles:
      - agent
      - default
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
